const GAMES_OVERAL_CARDS = [
  {
    language: "hindi",
    game: {
      title: "Hindi Alphabet Game",
      description:
        "Practise what you have learnt in your games and see if you can get the high score.",
      link: "/game/hindi_letter_game",
      link_info: "See game",
    },
  },
  {
    language: "urdu",
    game: {
      title: "Urdu Alphabet Game",
      description:
        "Practise what you have learnt in your games and see if you can get the high score.",
      link: "/game/urdu_aletter_game",
      link_info: "See game",
    },
  },
];

export default GAMES_OVERAL_CARDS;
