import { Inter } from "next/font/google";
import AuthProvider from "./(components)/AuthProvider";
import "./styles/globals.css";
//import Nav from "./(components)/Nav";
import Footer from "./(components)/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ScriptLit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          {/* <Nav /> */}
          <div className=" bg-whiter h-auto">{children}</div>
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
