import { Inter } from "next/font/google";
import AuthProvider from "./(components)/AuthProvider";
import "./styles/globals.css";
import NavBar from "./(components)/Nav";
import Footer from "./(components)/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Urdu App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <NavBar />
          <div className=" bg-whiter h-auto">{children}</div>
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
