import { Inter } from "next/font/google";
import "./styles/globals.css";
import NavBar from "./(components)/nav";
import Footer from "./(components)/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Urdu App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className=" bg-whiter">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
